version: "3.8"

services: 
  mosquitto_broker:
    restart: unless-stopped
    image: eclipse-mosquitto:2.0
    volumes:
      - ./mosquitto/config/:/mosquitto/config/
      - ./mosquitto/log:/mosquitto/log/
    ports:
      - "1883:1883"
      - "9001:9001"
    networks: 
      - default 
    expose:
      - "1883"

